apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detector
  namespace: mlops
  labels:
    app: fraud-detector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraud-detector
  template:
    metadata:
      labels:
        app: fraud-detector
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: fraud-api
          image: aziz293/fraud-detector:latest
          ports:
            - containerPort: 8080
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: fraud-api-secrets
                  key: api-token
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

